### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by zhouxiaowei** [epoll-j/bridge_webview_flutter#1]
➜  ios pod install
Analyzing dependencies
[!] No podspec found for `bridge_webview_flutter` in `.symlinks/plugins/bridge_webview_flutter/ios`

<img src="https://s1.ax1x.com/2020/04/20/JQOKpT.png" alt="JQOKpT.png" border="0" />

**Comment by epoll-j** [comment]
@zhouxiaowei 0.1.2版本修复了`bridge_webview_flutter: ^0.1.2`
