### ISSUE TITLE
dart 里 regisiterHandler 的方法 定义的有问题!

### ISSUE THREAD

**Issue by gaoxiao228** [epoll-j/bridge_webview_flutter#4]
现接口定义为:
webViewController.registerHandler("methodName", response: "r1", onCallBack: (callBackData) {
                print(callBackData.name); // handler name
                print(callBackData.data); // callback data ({'param': '1'})
            });
不应该是下面这样的吗?
webViewController.registerHandler("methodName", onCallBack: (data,callback) {
                print(data); 
                callback(something);
            });

**Comment by epoll-j** [comment]
这个库不再维护了，因为跟webview耦合度太高了，把jsbridge内容分离出来重写了一个[plugin](https://github.com/epoll-j/flutter_jsbridge_plugin)
